---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crispy_credits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crispy_credits
  template:
    metadata:
      labels:
        app: crispy_credits
    spec:
      containers:
      - name: crispy_credits
        image: rameshkumarverma/crispy_credits:latest
        ports:
        - containerPort: 8000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: crispy_credits-service
spec:
  selector:
    app: crispy_credits
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 8000
  type: LoadBalancer
